"""Cloudflare edge colo (IATA) -> city/country lookup for the location widget."""
COLO_MAP = {
    "FRA": ("Frankfurt", "Germany", "🇩🇪"),
    "AMS": ("Amsterdam", "Netherlands", "🇳🇱"),
    "LHR": ("London", "United Kingdom", "🇬🇧"),
    "CDG": ("Paris", "France", "🇫🇷"),
    "MAD": ("Madrid", "Spain", "🇪🇸"),
    "MXP": ("Milan", "Italy", "🇮🇹"),
    "VIE": ("Vienna", "Austria", "🇦🇹"),
    "WAW": ("Warsaw", "Poland", "🇵🇱"),
    "PRG": ("Prague", "Czechia", "🇨🇿"),
    "ZRH": ("Zurich", "Switzerland", "🇨🇭"),
    "STO": ("Stockholm", "Sweden", "🇸🇪"),
    "OSL": ("Oslo", "Norway", "🇳🇴"),
    "CPH": ("Copenhagen", "Denmark", "🇩🇰"),
    "HEL": ("Helsinki", "Finland", "🇫🇮"),
    "DUB": ("Dublin", "Ireland", "🇮🇪"),
    "BRU": ("Brussels", "Belgium", "🇧🇪"),
    "IST": ("Istanbul", "Turkey", "🇹🇷"),
    "DXB": ("Dubai", "United Arab Emirates", "🇦🇪"),
    "DOH": ("Doha", "Qatar", "🇶🇦"),
    "BAH": ("Manama", "Bahrain", "🇧🇭"),
    "TLV": ("Tel Aviv", "Israel", "🇮🇱"),
    "JED": ("Jeddah", "Saudi Arabia", "🇸🇦"),
    "RUH": ("Riyadh", "Saudi Arabia", "🇸🇦"),
    "IAD": ("Ashburn, VA", "United States", "🇺🇸"),
    "EWR": ("Newark, NJ", "United States", "🇺🇸"),
    "ORD": ("Chicago, IL", "United States", "🇺🇸"),
    "DFW": ("Dallas, TX", "United States", "🇺🇸"),
    "LAX": ("Los Angeles, CA", "United States", "🇺🇸"),
    "SJC": ("San Jose, CA", "United States", "🇺🇸"),
    "SEA": ("Seattle, WA", "United States", "🇺🇸"),
    "ATL": ("Atlanta, GA", "United States", "🇺🇸"),
    "MIA": ("Miami, FL", "United States", "🇺🇸"),
    "YYZ": ("Toronto", "Canada", "🇨🇦"),
    "YVR": ("Vancouver", "Canada", "🇨🇦"),
    "GRU": ("Sao Paulo", "Brazil", "🇧🇷"),
    "EZE": ("Buenos Aires", "Argentina", "🇦🇷"),
    "SCL": ("Santiago", "Chile", "🇨🇱"),
    "BOM": ("Mumbai", "India", "🇮🇳"),
    "MAA": ("Chennai", "India", "🇮🇳"),
    "DEL": ("New Delhi", "India", "🇮🇳"),
    "SIN": ("Singapore", "Singapore", "🇸🇬"),
    "HKG": ("Hong Kong", "Hong Kong", "🇭🇰"),
    "NRT": ("Tokyo", "Japan", "🇯🇵"),
    "KIX": ("Osaka", "Japan", "🇯🇵"),
    "ICN": ("Seoul", "South Korea", "🇰🇷"),
    "SYD": ("Sydney", "Australia", "🇦🇺"),
    "MEL": ("Melbourne", "Australia", "🇦🇺"),
    "JNB": ("Johannesburg", "South Africa", "🇿🇦"),
    "CAI": ("Cairo", "Egypt", "🇪🇬"),
    "MOW": ("Moscow", "Russia", "🇷🇺"),
    "THR": ("Tehran", "Iran", "🇮🇷"),
    "IKA": ("Tehran", "Iran", "🇮🇷"),
    "MCT": ("Muscat", "Oman", "🇴🇲"),
    "KWI": ("Kuwait City", "Kuwait", "🇰🇼"),
    "BEY": ("Beirut", "Lebanon", "🇱🇧"),
    "AMM": ("Amman", "Jordan", "🇯🇴"),
    "BGW": ("Baghdad", "Iraq", "🇮🇶"),
    "TBS": ("Tbilisi", "Georgia", "🇬🇪"),
    "EVN": ("Yerevan", "Armenia", "🇦🇲"),
    "BAK": ("Baku", "Azerbaijan", "🇦🇿"),
}

# country name -> ISO 3166-1 alpha-2, for the flag images
COUNTRY_CODE = {
    "Argentina": "AR", "Armenia": "AM", "Australia": "AU", "Austria": "AT",
    "Azerbaijan": "AZ", "Bahrain": "BH", "Belgium": "BE", "Brazil": "BR",
    "Canada": "CA", "Chile": "CL", "Czechia": "CZ", "Denmark": "DK",
    "Egypt": "EG", "Finland": "FI", "France": "FR", "Georgia": "GE",
    "Germany": "DE", "Hong Kong": "HK", "India": "IN", "Iran": "IR",
    "Iraq": "IQ", "Ireland": "IE", "Israel": "IL", "Italy": "IT",
    "Japan": "JP", "Jordan": "JO", "Kuwait": "KW", "Lebanon": "LB",
    "Netherlands": "NL", "Norway": "NO", "Oman": "OM", "Poland": "PL",
    "Qatar": "QA", "Russia": "RU", "Saudi Arabia": "SA", "Singapore": "SG",
    "South Africa": "ZA", "South Korea": "KR", "Spain": "ES", "Sweden": "SE",
    "Switzerland": "CH", "Turkey": "TR", "United Arab Emirates": "AE",
    "United Kingdom": "GB", "United States": "US",
}


def describe_colo(colo: str | None) -> dict:
    code = (colo or "").upper().strip()
    if code in COLO_MAP:
        city, country, flag = COLO_MAP[code]
        return {
            "colo": code,
            "city": city,
            "country": country,
            "country_code": COUNTRY_CODE.get(country, ""),
            "flag": flag,
        }
    return {"colo": code or "?", "city": "Unknown", "country": "Unknown", "country_code": "", "flag": "🏳️"}
