"""Cloudflare edge colo (IATA) -> city/country lookup for the location widget."""
COLO_MAP = {
    "FRA": ("Frankfurt", "Germany", "🇩🇪"),
    "AMS": ("Amsterdam", "Netherlands", "🇳🇱"),
    "LHR": ("London", "United Kingdom", "🇬🇧"),
    "CDG": ("Paris", "France", "🇫🇷"),
    "MAD": ("Madrid", "Spain", "🇪🇸"),
    "MXP": ("Milan", "Italy", "🇮🇹"),
    "VIE": ("Vienna", "Austria", "🇦🇹"),
    "WAW": ("Warsaw", "Poland", "🇵🇱"),
    "PRG": ("Prague", "Czechia", "🇨🇿"),
    "ZRH": ("Zurich", "Switzerland", "🇨🇭"),
    "STO": ("Stockholm", "Sweden", "🇸🇪"),
    "OSL": ("Oslo", "Norway", "🇳🇴"),
    "CPH": ("Copenhagen", "Denmark", "🇩🇰"),
    "HEL": ("Helsinki", "Finland", "🇫🇮"),
    "DUB": ("Dublin", "Ireland", "🇮🇪"),
    "BRU": ("Brussels", "Belgium", "🇧🇪"),
    "IST": ("Istanbul", "Turkey", "🇹🇷"),
    "DXB": ("Dubai", "United Arab Emirates", "🇦🇪"),
    "DOH": ("Doha", "Qatar", "🇶🇦"),
    "BAH": ("Manama", "Bahrain", "🇧🇭"),
    "TLV": ("Tel Aviv", "Israel", "🇮🇱"),
    "JED": ("Jeddah", "Saudi Arabia", "🇸🇦"),
    "RUH": ("Riyadh", "Saudi Arabia", "🇸🇦"),
    "IAD": ("Ashburn, VA", "United States", "🇺🇸"),
    "EWR": ("Newark, NJ", "United States", "🇺🇸"),
    "ORD": ("Chicago, IL", "United States", "🇺🇸"),
    "DFW": ("Dallas, TX", "United States", "🇺🇸"),
    "LAX": ("Los Angeles, CA", "United States", "🇺🇸"),
    "SJC": ("San Jose, CA", "United States", "🇺🇸"),
    "SEA": ("Seattle, WA", "United States", "🇺🇸"),
    "ATL": ("Atlanta, GA", "United States", "🇺🇸"),
    "MIA": ("Miami, FL", "United States", "🇺🇸"),
    "YYZ": ("Toronto", "Canada", "🇨🇦"),
    "YVR": ("Vancouver", "Canada", "🇨🇦"),
    "GRU": ("Sao Paulo", "Brazil", "🇧🇷"),
    "EZE": ("Buenos Aires", "Argentina", "🇦🇷"),
    "SCL": ("Santiago", "Chile", "🇨🇱"),
    "BOM": ("Mumbai", "India", "🇮🇳"),
    "MAA": ("Chennai", "India", "🇮🇳"),
    "DEL": ("New Delhi", "India", "🇮🇳"),
    "SIN": ("Singapore", "Singapore", "🇸🇬"),
    "HKG": ("Hong Kong", "Hong Kong", "🇭🇰"),
    "NRT": ("Tokyo", "Japan", "🇯🇵"),
    "KIX": ("Osaka", "Japan", "🇯🇵"),
    "ICN": ("Seoul", "South Korea", "🇰🇷"),
    "SYD": ("Sydney", "Australia", "🇦🇺"),
    "MEL": ("Melbourne", "Australia", "🇦🇺"),
    "JNB": ("Johannesburg", "South Africa", "🇿🇦"),
    "CAI": ("Cairo", "Egypt", "🇪🇬"),
    "MOW": ("Moscow", "Russia", "🇷🇺"),
    "THR": ("Tehran", "Iran", "🇮🇷"),
    "IKA": ("Tehran", "Iran", "🇮🇷"),
    "MCT": ("Muscat", "Oman", "🇴🇲"),
    "KWI": ("Kuwait City", "Kuwait", "🇰🇼"),
    "BEY": ("Beirut", "Lebanon", "🇱🇧"),
    "AMM": ("Amman", "Jordan", "🇯🇴"),
    "BGW": ("Baghdad", "Iraq", "🇮🇶"),
    "TBS": ("Tbilisi", "Georgia", "🇬🇪"),
    "EVN": ("Yerevan", "Armenia", "🇦🇲"),
    "BAK": ("Baku", "Azerbaijan", "🇦🇿"),
}


def describe_colo(colo: str | None) -> dict:
    code = (colo or "").upper().strip()
    if code in COLO_MAP:
        city, country, flag = COLO_MAP[code]
        return {"colo": code, "city": city, "country": country, "flag": flag}
    return {"colo": code or "?", "city": "Unknown", "country": "Unknown", "flag": "🏳️"}
